{% set version = "1.7-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rrcov
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rrcov_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rrcov/rrcov_{{ version }}.tar.gz
  sha256: dfc595077fb65eb12653d994c757e0998c09a186575d5b61000bb5452fd0b033

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-lattice                        # [build_platform != target_platform]
    - r-mvtnorm                        # [build_platform != target_platform]
    - r-pcapp                          # [build_platform != target_platform]
    - r-robustbase                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - libblas
    - r-base
    - r-lattice
    - r-mvtnorm
    - r-pcapp
    - r-robustbase >=0.92.1
  run:
    - r-base
    - r-lattice
    - r-mvtnorm
    - r-pcapp
    - r-robustbase >=0.92.1

test:
  commands:
    - $R -e "library('rrcov')"           # [not win]
    - "\"%R%\" -e \"library('rrcov')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rrcov
  license: GPL-2.0-or-later
  summary: Robust Location and Scatter Estimation and Robust Multivariate Analysis with High Breakdown Point.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
