{% set version = '1.4-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rrcov
  version: {{ version|replace("-", "_") }}

source:
  fn: rrcov_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rrcov_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rrcov/rrcov_{{ version }}.tar.gz
  sha256: 8569e00ec8a86db8db4fcb8a74bc81314ef2b53fa3a284a02ad37f103782c572

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cluster
    - r-lattice
    - r-mvtnorm
    - r-pcapp
    - r-robustbase >=0.92_1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-cluster
    - r-lattice
    - r-mvtnorm
    - r-pcapp
    - r-robustbase >=0.92_1

test:
  commands:
    - $R -e "library('rrcov')"           # [not win]
    - "\"%R%\" -e \"library('rrcov')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rrcov
  license: GPL (>= 2)
  summary: Robust Location and Scatter Estimation and Robust Multivariate Analysis with High
    Breakdown Point.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
