travis:
  secure:
    BINSTAR_TOKEN: HeHO6nc18qi83FEDMEqq5ydeJFK8cjc7ynzemk4t0N2iD1KRC9sRcKsQrZC5TGAs9Knt80mW/alVWw3fJ/Yxjox1UFWsKNvd8GFpd5mMwGixaiRDWnvRPGCo7IZDoF1h1k33kVdHIR8usuuQ2UospotFkmiWs6YyaR4iNSoU5y7zyGgMb+mgtWJ1UHPULEnEUOApcL6iRq74vH+7DaRVRTNgruwQ6QikLHFlDQbXp+AyKdqv7UDjPxFgTCDjBXCLbuQ2GPntoPQEc/1TFNpRhlcfziylnRSS2nAzuTLQKPfslBjcrrqlxp8w+SYvt7vqDLfKJjpAvzvo9W1GBoA2qs7OmLAnONqzUqh1dEZjW9NN5w6duafCejfF8NQXF/Frt7+Csa/yP5rqkpsFZZhv+11T+t5MXalc3VMILCfBF5inWpemwCeNNpWbh0PgWnk9/tp+aQ0U8RJGNdXBShMzWji79M8Fl6aA6FjMjwzEEUK1MMTKYCR1uC9Ln5d3+eFuvUReeY5k8BDfBfy1y3C6X4XfbGGhYwD/vqb3bnwID5fVUdTxLjm0CeRZmqUhQ4pDia0/D1ja2tCRYqipsFSzzQVeuFCBNkIJtUuQ3ulDxCzcqsd+EG/15EV8mFvFUDSCiGv418uwcW1B/vsmgRRPICH9JBi1eBOQij8uLCxI0c4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
