appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: I7eQIkQipl2VMFkLB1idWzepL13xFVg+9R004tf5mAXLCsApY1KctjaFqylrgLA0v018EEHbXQtE7zDyAcoE2I6ZDGjx+DudehAba3Tm2QgzN6H43lNfRzHBueGqTwB0TTTIkmRIwrPCocHcefA+5I4RJsIbc6hhc1Y3yN+CVyMgEEGxb1qGoI1vSrpA2Tq3+je5SMt9QgujPhWrTktTn3PzsyXVPfDj+2fpxdd8MMdNoxsMbfI6MyDg6M5Dw+bnrdiBSNfKMbUCfv58jPWtsu6PbhzhTMmJlcofNlrFBSpi2aBrgbTMVBxDAVb3Z5ONEuwMbdXp2FyzrIxDKrhST9KmtFpOHGeFzTfrGLm0LkboNpwPn7keaaDHuBtM1N8MfyAEuFj7yLaQ2XzqnNdoE/rbCzTEtoPriueztVQjjdH3qGXK+FBobU9SqVX9nUOQOJReYTqSLkuMBqole7BQCwxMHDniScifzFZSLphNWy1zDCSOfdzTOATdDcWFDvV/XsmWg3oy8sYzj21pxxPcMwgNFQsnSPH5n8o9C8Bw3kj7rwuRRsAVy+p+F1tZXd7ACyw9i9Ta74Zqqk+tM2rh8cTT5rrN90gDbCcMhf3GaAq9IvOCEKEp0jBB4N/hKJI0+64AG/qtA3aJn4N9hnCV+cBNr3hgJQny4ziO1aHQcnY=
